# Generated by Django 4.0.3 on 2022-03-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pubkey', models.CharField(max_length=50)),
                ('stacking_nft_count', models.IntegerField()),
                ('user_signature', models.TextField()),
                ('firth_stacking_data', models.DateTimeField(auto_now_add=True)),
                ('stacking_data_updated_at', models.DateTimeField(auto_now=True)),
                ('nft_image', models.ImageField(upload_to='nfts_img/')),
                ('firth_stacking_duration', models.DurationField()),
                ('is_stacking_active', models.BooleanField(default=False)),
            ],
        ),
    ]
